max_width = 160
newline_style = "Unix" # Prevent carriage returns
single_line_if_else_max_width = 80
use_small_heuristics = "Max" # The default setting has a heuristic which splits lines too aggresively
