[package]
name = "deadpool-diesel-async"
version = "0.3.0"
authors = ["Trey Lowerison <trey@sidechainme.com>"]
edition = "2021"

[dependencies]
deadpool = { version = "0.9.3", features = ["managed", "rt_tokio_1"] }
diesel = { version = "2.0.0-rc.1", default-features = false }
diesel-async = { git = "https://github.com/weiznich/diesel_async", rev = "acf3ed3", default-features = false }
thiserror = "1.0.30"
tokio = "1.17.0"

[features]
mysql = ["diesel/mysql", "diesel-async/mysql"]
postgres = ["diesel/postgres", "diesel-async/postgres"]
serde = ["deadpool/serde"]
